# Generated by Django 3.2.6 on 2021-09-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
