# Generated by Django 3.2.6 on 2021-10-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
