# Generated by Django 3.2.6 on 2021-11-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iran_zone', '0002_auto_20211105_1231'),
        ('account', '0006_auto_20211112_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.ForeignKey(default=394, null=True, on_delete=django.db.models.deletion.CASCADE, to='iran_zone.shahr', verbose_name='شهر'),
        ),
    ]
