version: "3.7"

services:
  django_web_poya:
    build: .
    command: >
      ash -c "python manage.py migrate &&  gunicorn BiaBegard.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static
      - media:/app/static_cdn/media_root
      - .:/app/
    ports:
      - 8010:8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=biabegard
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/static_cdn/media_root
      - ./nginx/config/:/etc/nginx/conf.d/
    ports:
      - 8000:80
    depends_on:
      - django_web_poya
  redis:
    image: redis:alpine
    volumes:
      - redis_val:/data
  celery:

    restart: always
    build:
      context: .
#      dockerfile: dokckerfile-name-alternative
#      args:
#        name : ashkan
    command: >
      ash -c "touch celery.log &&  celery -A BiaBegard worker -l info &> celery.log"
    volumes:
      - .:/app
    depends_on:
      - django_web_poya
      - redis
volumes:
  postgres_data:
  static:
  media:
  redis_val:
