# Generated by Django 3.2.6 on 2021-10-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_alter_blog_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='توضیحات کوتاه(یک پاراگراف)'),
        ),
    ]
