# Generated by Django 3.2.6 on 2021-10-04 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_blog', '0005_auto_20211003_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان نظر')),
                ('description', models.TextField(verbose_name='متن اصلی نظر')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد نظر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='api_blog.blog', verbose_name='کاربر مربوطه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مربوطه')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
