# Generated by Django 3.2.6 on 2021-11-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ostan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام استان')),
            ],
        ),
        migrations.CreateModel(
            name='Shahrestan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهرستان')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iran_zone.ostan', verbose_name='استان مربوطه')),
            ],
        ),
        migrations.CreateModel(
            name='Shahr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iran_zone.ostan', verbose_name='استان مربوطه')),
                ('shahrestan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iran_zone.shahrestan', verbose_name='شهرستان مربوطه')),
            ],
        ),
        migrations.CreateModel(
            name='Dehestan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دهستان')),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iran_zone.ostan', verbose_name='استان مربوطه')),
                ('shahrestan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iran_zone.shahrestan', verbose_name='شهرستان مربوطه')),
            ],
        ),
    ]
