# Generated by Django 3.2.6 on 2021-11-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iran_zone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dehestan',
            options={'verbose_name': 'دهستان', 'verbose_name_plural': 'دهستان ها'},
        ),
        migrations.AlterModelOptions(
            name='ostan',
            options={'verbose_name': 'استان', 'verbose_name_plural': 'استان ها'},
        ),
        migrations.AlterModelOptions(
            name='shahr',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='shahrestan',
            options={'verbose_name': 'شهرستان', 'verbose_name_plural': 'شهرستان ها'},
        ),
    ]
