# Generated by Django 3.2.6 on 2021-09-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offs',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد های تخفیف'},
        ),
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'verbose_name': 'جزئیات پرداخت', 'verbose_name_plural': 'جزئیات پرداخت'},
        ),
    ]
