# Generated by Django 3.2.6 on 2021-09-14 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_alter_post_options'),
        ('financial', '0002_auto_20210910_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='financial.orders', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='offs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.offs', verbose_name='کد تخفیف '),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shipping.post', verbose_name='پست شونده'),
        ),
    ]
