# Generated by Django 3.2.6 on 2021-08-19 15:09

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته بندی')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.category', verbose_name='دسته بندی والد')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='CategoryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=150, verbose_name='نام نوع دسته بندی')),
                ('have_subcategory', models.BooleanField(default=False, verbose_name='زیر دسته بندی داشته / نداشته باشد؟')),
            ],
            options={
                'verbose_name': 'نوع دسته بندی',
                'verbose_name_plural': 'انواع دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('image', models.ImageField(upload_to=utils.upload_image_path, verbose_name='کاور اصلی محصول')),
                ('inventory', models.IntegerField(verbose_name='موجودی محصول')),
                ('short_description', models.TextField(max_length=700, verbose_name='توضیحات کوتاه محصول')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات کامل محصول')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد محصول')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('product_price', models.FloatField(verbose_name='قیمت محصول')),
                ('off_price', models.FloatField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('off_expired_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضاء تخفیف')),
                ('category', models.ManyToManyField(to='content.Category', verbose_name='دسته بندی مربوطه')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='فروشنده محصول')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='PricesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.FloatField(default=0, verbose_name='قیمت محصول')),
                ('modified_date', models.DateField(auto_now_add=True, verbose_name='زمان ثبت تغییرات قیمت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price_history', to='content.products', verbose_name='محصول مربوطه')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='content.categorytype'),
        ),
    ]
