# Generated by Django 3.2.6 on 2021-08-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='آدرس در URL'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='content.categorytype', verbose_name='نوع دسته بندی'),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(null=True, verbose_name='عنوان در url')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('products', models.ManyToManyField(blank=True, to='content.Products', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'تگ/برچسب',
                'verbose_name_plural': 'تگ ها / برچسب ها',
            },
        ),
    ]
