# Generated by Django 3.2.6 on 2021-08-23 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210820_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='type_name',
            field=models.CharField(max_length=150, unique=True, verbose_name='نام نوع دسته بندی'),
        ),
        migrations.AlterField(
            model_name='products',
            name='off_price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.FloatField(default=0, verbose_name='قیمت محصول'),
        ),
        migrations.CreateModel(
            name='ProductsGalleries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان عکس')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر محصول')),
                ('active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.products', verbose_name='محصول مربوطه')),
            ],
        ),
    ]
