# Generated by Django 3.2.6 on 2021-08-25 13:49

from django.db import migrations, models
import django_jalali.db.models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210823_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='created_by',
            new_name='supplier',
        ),
        migrations.AddField(
            model_name='category',
            name='calender',
            field=django_jalali.db.models.jDateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productsgalleries',
            name='image',
            field=models.ImageField(upload_to=utils.upload_image_path, verbose_name='تصویر محصول'),
        ),
    ]
