# Generated by Django 3.2.6 on 2021-08-28 06:38

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210825_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='calender',
        ),
        migrations.AddField(
            model_name='products',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک های محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='created_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='off_expired_time',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان انقضاء تخفیف'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created_time',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
    ]
