# Generated by Django 3.2.6 on 2021-09-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_productsgalleries_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='tag', to='content.Products', verbose_name='محصولات'),
        ),
    ]
