# Generated by Django 3.2.6 on 2021-10-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_tags_products'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='id_for',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='type',
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.products', verbose_name='محصولات'),
        ),
    ]
