# Generated by Django 3.2.6 on 2021-09-08 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(choices=[('post', 'post'), ('pishtaz', 'pishtaz'), ('aadi', 'aadi'), ('ersal_forooshgahi', 'ersal_forooshgahi'), ('ersal_pekmotori', 'ersal_peykmotori ')], max_length=20)),
                ('time_recived', models.CharField(choices=[('صبح', '۸ تا ۱۲ بعد از ظهر'), ('ظهر', '۱۲ تا ۶ عصر'), ('شب', '۶ عصر تا ۱۲ شب')], max_length=3)),
                ('date_recived', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
