# Generated by Django 3.2.6 on 2021-09-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'نحوه ارسال', 'verbose_name_plural': 'نحوه ارسال'},
        ),
    ]
