# Generated by Django 3.2.6 on 2021-11-01 12:41

import ckeditor_uploader.fields
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سایت')),
                ('logo', models.ImageField(upload_to=utils.upload_image_path, verbose_name='لوگوی سایت')),
                ('about_us', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='درباره سایت')),
                ('address', models.TextField(verbose_name='آدرس سایت')),
                ('telephone', models.PositiveBigIntegerField(verbose_name='تلفن سایت')),
                ('mobile', models.PositiveBigIntegerField(verbose_name='تلفن همراه')),
                ('fax', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='فکس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل سایت')),
            ],
        ),
    ]
