# Generated by Django 3.2.6 on 2021-11-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'تنطیمات سایت', 'verbose_name_plural': 'تنطیمات سایت'},
        ),
    ]
